version: "3.8"

services:
  service1:
    image: haquocdat543/repo:node
    ports:
      - 8085:8085
    networks:
      - net1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.2'
          memory: 50MB	
      restart_policy:
        condition: on-failure
networks:
  net1:
    driver: overlay
    name: www-net1
